name: polymer_mx
version: 0.0.1
description: |
  MX Components
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  slickdart:
    path: ../slickdart
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.6
  web_components: ^0.12.2+1
  polymer: ^1.0.0-rc.12
  reflectable: ^0.5.0
  selectize:
      git: https://github.com/cjkao/selectize.git
#  polymer_datepicker: ^0.9.2
  autonotify_observe: ^1.0.0
#  less_dart: any
transformers:
#- less_dart
- polymer:
    entry_points: web/index.html
    entry_points: combobox/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
